export const LOAD_COUNTRIES_SUCCESS = "LOAD_COUNTRIES_SUCCESS";
export const GET_IP_TRANSACTION_SUCCESS = "GET_IP_TRANSACTION_SUCCESS";
export const GET_COUNTRY_TRANSACTION_SUCCESS =
  "GET_COUNTRY_TRANSACTION_SUCCESS";
